/**
 * Neovim Configuration Generator
 *
 * Generates a neovim.lua plugin configuration file from theme JSON.
 * Supports:
 * - Plugin repository specification
 * - Colorscheme with light/dark variants
 * - Custom plugin options
 */

import type { ThemeJson, ThemeNeovimConfig, ThemeMode } from "../../types/theme-schema";

/**
 * Serializes a JavaScript value to Lua code
 */
function toLua(value: unknown, indent = 2): string {
  const spaces = " ".repeat(indent);

  if (value === null || value === undefined) {
    return "nil";
  }

  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }

  if (typeof value === "number") {
    return String(value);
  }

  if (typeof value === "string") {
    // Escape quotes and backslashes
    const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `"${escaped}"`;
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "{}";
    }
    const items = value.map((v) => `${spaces}${toLua(v, indent + 2)}`);
    return `{\n${items.join(",\n")}\n${" ".repeat(indent - 2)}}`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) {
      return "{}";
    }
    const items = entries.map(([k, v]) => {
      // Use bracket notation for keys that aren't valid Lua identifiers
      const key = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k) ? k : `["${k}"]`;
      return `${spaces}${key} = ${toLua(v, indent + 2)}`;
    });
    return `{\n${items.join(",\n")}\n${" ".repeat(indent - 2)}}`;
  }

  return "nil";
}

/**
 * Generates the plugin options section if present
 */
function generateOptsSection(opts: Record<string, unknown> | undefined): string {
  if (!opts || Object.keys(opts).length === 0) {
    return "";
  }

  return `    opts = ${toLua(opts, 6)},`;
}

/**
 * Generates a neovim.lua configuration file for a theme
 */
export function generateNeovimConfig(theme: ThemeJson, mode: ThemeMode): string {
  if (!theme.neovim) {
    return "";
  }

  const { repo, colorscheme, light_colorscheme, opts } = theme.neovim;

  // Determine which colorscheme to use based on mode
  const effectiveColorscheme =
    mode === "light" && light_colorscheme ? light_colorscheme : colorscheme;

  const optsSection = generateOptsSection(opts);

  const lines = [
    `-- ${theme.title} (${mode}) - Generated by FormalConf`,
    `-- Neovim colorscheme configuration for LazyVim`,
    ``,
    `return {`,
    `  {`,
    `    "${repo}",`,
    `    name = "${theme.title.toLowerCase().replace(/\s+/g, "-")}",`,
    `    priority = 1000,`,
  ];

  if (optsSection) {
    lines.push(optsSection);
  }

  lines.push(
    `  },`,
    `  {`,
    `    "LazyVim/LazyVim",`,
    `    opts = {`,
    `      colorscheme = "${effectiveColorscheme}",`,
    `    },`,
    `  },`,
    `}`
  );

  return lines.join("\n") + "\n";
}

/**
 * Generates a dual-mode neovim.lua that handles both light and dark modes
 * using auto-dark-mode.nvim or similar detection
 */
export function generateDualModeNeovimConfig(theme: ThemeJson): string {
  if (!theme.neovim) {
    return "";
  }

  const { repo, colorscheme, light_colorscheme, opts } = theme.neovim;

  // If no light colorscheme specified, use the same for both
  const lightScheme = light_colorscheme || colorscheme;

  const optsSection = generateOptsSection(opts);

  const lines = [
    `-- ${theme.title} - Generated by FormalConf`,
    `-- Neovim colorscheme configuration with light/dark mode support`,
    ``,
    `return {`,
    `  {`,
    `    "${repo}",`,
    `    name = "${theme.title.toLowerCase().replace(/\s+/g, "-")}",`,
    `    priority = 1000,`,
  ];

  if (optsSection) {
    lines.push(optsSection);
  }

  lines.push(
    `  },`,
    `  {`,
    `    "LazyVim/LazyVim",`,
    `    opts = {`,
    `      colorscheme = "${colorscheme}",`,
    `    },`,
    `  },`
  );

  // Add auto-dark-mode if light colorscheme is different
  if (light_colorscheme && light_colorscheme !== colorscheme) {
    lines.push(
      `  -- Optional: auto-dark-mode.nvim for automatic switching`,
      `  -- Uncomment if you want Neovim to follow system theme`,
      `  -- {`,
      `  --   "f-person/auto-dark-mode.nvim",`,
      `  --   opts = {`,
      `  --     update_background = true,`,
      `  --     set_dark_mode = function()`,
      `  --       vim.api.nvim_set_option_value("background", "dark", {})`,
      `  --       vim.cmd("colorscheme ${colorscheme}")`,
      `  --     end,`,
      `  --     set_light_mode = function()`,
      `  --       vim.api.nvim_set_option_value("background", "light", {})`,
      `  --       vim.cmd("colorscheme ${lightScheme}")`,
      `  --     end,`,
      `  --   },`,
      `  -- },`
    );
  }

  lines.push(`}`);

  return lines.join("\n") + "\n";
}

/**
 * Checks if a theme has Neovim configuration
 */
export function hasNeovimConfig(theme: ThemeJson): boolean {
  return !!theme.neovim?.repo && !!theme.neovim?.colorscheme;
}
